### ISSUE TITLE
Helm guide still there (404) via search

### ISSUE THREAD

**Issue by wasaga** [pomerium/documentation#100]
Page: https://www.pomerium.com/docs/k8s/helm

## What's incorrect or missing

<img width="654" alt="image" src="https://user-images.githubusercontent.com/673131/184211295-ba17dbee-2c12-48c8-b0c3-e5e07e5ea6e8.png">

## What's the resolution?

Probably has to be removed from the index? This is not the only page that's still in the index yet does not exist anymore.

**Comment by alexfornuto** [comment]
Resolution:

 - Re-crawled the docs site
 - The helm page is still indexed, because it wasn't removed. It was moved to guides with a deprecation note added.
 - After re-crawl, it shows up in search in the proper place.
