### ISSUE TITLE
cache bust search index when pushing to main

### ISSUE THREAD

**Issue by desimone** [pomerium/documentation#102]
## What's incorrect or missing

Currently, we don't cache bust our algolia index when updates are made resulting in stale data being our index. 

## What's the resolution?

Cache bust on pushes to main, possibly through a github action. 

## Related

- https://github.com/pomerium/documentation/issues/100
- https://pomerium-com.slack.com/archives/C0277SH5KL3/p1660253979059029?thread_ts=1660242152.058519&cid=C0277SH5KL3

**Comment by alexfornuto** [comment]
Looks like we could also schedule the crawler to re-crawl every day: https://www.algolia.com/doc/tools/crawler/apis/configuration/schedule/

**Comment by desimone** [comment]
A re-crawl might be easier / more idiot proof.

**Comment by alexfornuto** [comment]
I just set `schedule: 'every 1 day at 12:00 am',` in the crawler. Not sure what timezone it's using.

**Comment by desimone** [comment]
That works.
