### ISSUE TITLE
k8s: docs/reference/certificates

### ISSUE THREAD

**Issue by wasaga** [pomerium/documentation#1094]
Page: docs/reference/certificates

<img width="935" alt="image" src="https://github.com/pomerium/documentation/assets/673131/bd40b5c2-2750-4a1b-9b1a-f2c5b2275069">

## What's incorrect or missing

kubernetes:
1. Yaml keys should not be capitalized
2. Yaml presented is in fact an example, not a definition. 
3. the link should be "Kubernetes CRD refrence", as it's not an ingress setting

**Comment by ZPain8464** [comment]
Fixed in #980
