### ISSUE TITLE
groups: PPL criterion is not documented

### ISSUE THREAD

**Issue by wasaga** [pomerium/documentation#1146]
Page: https://www.pomerium.com/docs/capabilities/ppl#criteria

## What's incorrect or missing

`groups` criterion is not documented

<img width="983" alt="image" src="https://github.com/pomerium/documentation/assets/673131/488d35c5-d3d0-41f9-a772-1b4c1b79a48d">

**Comment by desimone** [comment]
Technically says "all the open source criteria" but we might as well list it out.
