### ISSUE TITLE
docs: recommend using the route logout

### ISSUE THREAD

**Issue by desimone** [pomerium/documentation#120]
There was a bug causing logout on the authenticate service to work differently from logout on the proxy service. (they were actually using different sessions) The above PR should fix that problem.

However using logout from authenticate is not ideal. It can't delete the cookie on the route itself, and we utilize a caching layer for session access, so it may take a few seconds for the user to appear logged out on the route. We should update the documentation to recommend using the route logout.

_Originally posted by @calebdoxsey in https://github.com/pomerium/pomerium/issues/3592#issuecomment-1239655500_

**Comment by calebdoxsey** [comment]
I don't know where to document this. We don't actually recommend using the authenticate sign_out endpoint anywhere.

**Comment by desimone** [comment]
Let's add some text to the single sign out docs page.

**Comment by alexrudd2** [comment]
@XxEnigmaticxX ket's keep an eye on this.  Currently I just redirect people to `https://authenticate.<domain>.com/.pomerium/` but the logout link isn't obvious (it's upper-right under the user gravatar)

**Comment by ZPain8464** [comment]
Fixes this: https://github.com/pomerium/documentation/pull/429

@desimone I believe we can close this?
