### ISSUE TITLE
Troubleshooting upstream errors

### ISSUE THREAD

**Issue by nhayfield** [pomerium/documentation#1404]
We want to do a new section for docs for upstream errors.
We split the Core pomerium errors to two pages now. All normal errors and Upstream connection errors.
The goal was to have less people contact us  when the issue is on there upstream servers side.

Prior art:
https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#error-521-web-server-is-down

Error codes and descriptions from Envoy:
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/response_code_details
We are only counting the around 7 codes that have 'upstream' in them.

**Comment by ZPain8464** [comment]
These docs are ready, but I haven't merged the Troubleshooting / Zero FAQ docs until we decide where these docs should live. See https://github.com/pomerium/documentation/pull/1426 for more information.
