### ISSUE TITLE
Search result for `replica` redirects to the non-existent page

### ISSUE THREAD

**Issue by ssveta7ak** [pomerium/documentation#1497]
Video
https://www.loom.com/share/079840f0d77343e1842b4b19c9c1d079?sid=4ec7b957-2903-48db-90ae-f8c5c4643501

## What's incorrect or missing
When the user searches for documentation using the keyword replica and clicks the left mouse button, they are redirected to a "Page not found" page. However, if the user opens the page in a new tab, it works correctly.

![Screenshot from 2024-07-04 17-53-26](https://github.com/pomerium/documentation/assets/37595288/c37ed234-bce2-408f-a23f-3e458478d09f)

![Screenshot from 2024-07-04 17-53-32](https://github.com/pomerium/documentation/assets/37595288/4d54d8d6-e20b-49ca-9475-6e05637b5124)

**Comment by ZPain8464** [comment]
I noticed when you open the page in the same tab, the URL doesn't redirect at all, as the rule doesn't seem to apply. It goes to `/docs/deploy/k8s/install`. This makes sense given that when you search in the Algolia "Search docs" field, you can see that Algolia still indexes the "old" link:

![SCR-20240705-jdsf](https://github.com/pomerium/documentation/assets/60552605/f8d36fdd-ebd1-4459-9070-2bbbc512bd9b)

What's weird is that using Ctrl+Click to open in a new tab does redirect correctly as you've shown. I'll take have to take a deeper look, as it could have something to do with how Netlify redirect rules are applied, Algolia, or both.

**Comment by ZPain8464** [comment]
The Algolia crawler was blocked. I had to restart it, so it will crawl again at its scheduled time tonight. If this doesn't fix the issue, I'll look into it more.

**Comment by ZPain8464** [comment]
Fixed. 
![fixed-index](https://github.com/pomerium/documentation/assets/60552605/580e468f-fb72-4edc-b508-5629a363d113)

**Comment by ssveta7ak** [comment]
Checked.
