### ISSUE TITLE
k8s reference code generates malformed JSX

### ISSUE THREAD

**Issue by desimone** [pomerium/documentation#174]
## What's incorrect or missing

The new kubernetes reference table generates invalid HTML / JSX> 

## What's the resolution?

```bash
Expected corresponding JSX closing tag for <tbody>. (187:3)
  185 |   </tbody>
  186 | `}</code></pre>
> 187 |    </table>
      |    ^
  188 | <h3 {...{"id":"cookie"}}><inlineCode parentName="h3">{`cookie`}</inlineCode></h3>
  189 | <p>{`Cookie defines Pomerium session cookie options.`}</p>
  190 | <table>
```

https://github.com/pomerium/documentation/blob/7ab684bdd24d179eca59d1e3cb04c7edd9aa9fc8/content/docs/deploying/k8s/reference.md

## Related 

#171

**Comment by wasaga** [comment]
I don't see anything like that error.
