### ISSUE TITLE
Broken Links for archived versions

### ISSUE THREAD

**Issue by husira** [pomerium/documentation#195]
Page: https://www.pomerium.com/docs/versions

## What's incorrect or missing

Links for archived versions do not work for version v0.17.x, v0.18.x & v0.19.x.
Links for archived version v0.16.x and older work so far.

## What's the resolution?

Fixing the links for archived versions starting at version v0.17.x.

**Comment by desimone** [comment]
Thanks for reporting the issue.

- https://0-17-0.docs.pomerium.com/docs/
- https://0-16-0.docs.pomerium.com/docs/
- https://0-15-0.docs.pomerium.com/docs/
- https://0-14-0.docs.pomerium.com/docs/
- ... all the way back to  v0.2.0!
- https://0-2-0.docs.pomerium.com/

And so on. 

Unfortunately, 18 and 19 tags need to be created and domains pushed.

**Comment by desimone** [comment]
Related...

- https://github.com/pomerium/documentation/issues/194

**Comment by husira** [comment]
Thank you for your help.

**Comment by desimone** [comment]
- https://0-18-0.docs.pomerium.com/docs/
- https://0-19-0.docs.pomerium.com/docs/
- https://0-20-0.docs.pomerium.com/docs/

Have been added.
