### ISSUE TITLE
Bing serves lots of legacy subdomains in results

### ISSUE THREAD

**Issue by wasaga** [pomerium/documentation#211]
Bing is default for Edge on Windows. 

It currently serves all kinds of subdomains on first page of results for Pomerium 

![image.png](https://images.zenhubusercontent.com/600622a9c28f517c8c6081c9/31a5cb32-afc9-4e04-832c-5c84394ea7c1)

**Comment by desimone** [comment]
Should be helped by #190

**Comment by desimone** [comment]
Reindexing; might need to blacklist the io domain.

**Comment by desimone** [comment]
![Screenshot 2022-12-21 at 3.19.12 PM.png](https://images.zenhubusercontent.com/544ecc9d7c6ccc6277a58e6d/8fecf099-4005-4eb0-8c71-5dce7d525e06)
