### ISSUE TITLE
integrate cspell

### ISSUE THREAD

**Issue by wasaga** [pomerium/documentation#237]
There are some spelling errors in the docs. 
We should add `cspell` or other spell checker to the build. 

i.e. see how Facebook's repo does that https://github.com/facebook/docusaurus/search?q=cspell

**Comment by calebdoxsey** [comment]
so many false positives. the word list will be very large.

**Comment by calebdoxsey** [comment]
it doesn't understand things like:

```
    Authorization: Basic cm9vdDpodW50ZXI0Mg==
```

I'm not sure how to provide an override without it showing up in the docs themselves, which we don't want.

**Comment by calebdoxsey** [comment]
turns out we can add directives to the front matter in md files

**Comment by desimone** [comment]
Should we add a precommit check to keep things pristine?
