### ISSUE TITLE
New Doc: Health Checks and Load Balancing

### ISSUE THREAD

**Issue by alexfornuto** [pomerium/documentation#3]
Create a new page (likely under topics), which covers in more detail our load balancing and health check options. Discuss what Envoy settings we set based on the keys we provide to the user, and link to Envoy's docs for more information on how those config options work.

**Comment by wasaga** [comment]
- https://docs.pomerium.com/docs/k8s/ingress#load-balancing
- https://docs.pomerium.com/docs/topics/load-balancing
