### ISSUE TITLE
add JWT validation rules

### ISSUE THREAD

**Issue by wasaga** [pomerium/documentation#326]
## What's incorrect or missing

We speak of validating JWT authenticity using signing key from authenticate. 
We also need elaborate on the need to validate `audience` and `issuer`.

**Comment by desimone** [comment]
More context in slack
- https://pomerium-com.slack.com/archives/C012D1Q96TX/p1674074849305369

**Comment by ZPain8464** [comment]
PR here: https://github.com/pomerium/documentation/pull/415
