### ISSUE TITLE
There aren't links to the repositories in the Download section 

### ISSUE THREAD

**Issue by ssveta7ak** [pomerium/documentation#328]
https://www.pomerium.com/docs/deploying/binary

## What's incorrect or missing

In the Download section, GitHub and Cloudsmith don't contain links to the package's repositories.

## What's the resolution?

Add links to the repositories.

**Comment by desimone** [comment]
I think perhaps we should have a table of all the current releases, for all products, and their download links on the main "releases" page.

https://www.pomerium.com/docs/releases

**Comment by ZPain8464** [comment]
Was just creating a branch for this fix. I think we should also add the links to `/docs/deploying/binary` in addition to the `/docs/releases` page. What do you think?

**Comment by ZPain8464** [comment]
@desimone I will make a separate PR for the releases table.
