### ISSUE TITLE
Incorrect example  screen in the Quickstart Pomerium Core using Docker documentation

### ISSUE THREAD

**Issue by ssveta7ak** [pomerium/documentation#369]
Page: https://www.pomerium.com/docs/quickstart

## What's incorrect or missing

Quick start promise that after authorization user will be redirected to the route defined in the policy.
But the example shows a different screen (User details)

![image.png](https://images.zenhubusercontent.com/63bc6de617e71f0442fdda1c/c2215adb-0bf9-49c6-9b50-27afec49bbdc)

**Comment by ZPain8464** [comment]
https://github.com/pomerium/documentation/pull/384 Fixes this issue
