### ISSUE TITLE
Timeout config names

### ISSUE THREAD

**Issue by mnestor** [pomerium/documentation#391]
Page: [https://www.pomerium.com/docs/${page}](https://github.com/pomerium/documentation/blob/main/content/docs/reference/global-timeouts.md)

## What's incorrect or missing

Config names are referenced 2 different way. I believe they should be `<type>_timeout` instead of `timeout_<type>` but then the ENV variables might need to change. Since I don't use ENV variables I'm not sure which way they should go and I cannot find reference to them in the code.

## What's the resolution?

Changing the timeout variables to be the right way in the same format in both locations on the page. Since I cannot determine the right way for the ENV I hesitate to submit an incomplete PR for this.

**Comment by desimone** [comment]
Updated your issue. It looks like markdown chewed up the <type>
