### ISSUE TITLE
Docs: update Signing Key reference in Enterprise GUI Config

### ISSUE THREAD

**Issue by ZPain8464** [pomerium/documentation#483]
References this PR: https://github.com/pomerium/pomerium-console/pull/3244#pullrequestreview-1331332691

- [ ] #505
- [ ] #506
- [ ] #507

**Comment by desimone** [comment]
We need to make several changes here.

- [ ] docs: move sign out and jwks urls to route based (not authenticate)
- [ ] docs: authenticate service url is not required for device registration anymore (it's route based)
- [ ] docs: update references to jwks endpoint, authenticate-service-url no longer required and is inferred from `iss` claim and lives on the route endpoint

**Comment by ZPain8464** [comment]
@desimone let me know what needs to updated and I can make changes.
