### ISSUE TITLE
docs: update docs / guides sign out endpoint is route based, `authenticate-service-url` is not required

### ISSUE THREAD

**Issue by desimone** [pomerium/documentation#505]

**Comment by ZPain8464** [comment]
The single sign-out docs were already updated to instruct users to use the external route URL (see [here](https://www.pomerium.com/docs/capabilities/single-sign-out)), not the authenticate service URL.

**Comment by ZPain8464** [comment]
@desimone the single sign-out docs were already updated to instruct users to configure sign out with the `/.pomerium/sign_out` URL. See [Single Sign-out](https://www.pomerium.com/docs/capabilities/single-sign-out)
