### ISSUE TITLE
The links don't display page information correctly.

### ISSUE THREAD

**Issue by ssveta7ak** [pomerium/documentation#557]
https://www.pomerium.com/docs/reference/routes/health-checks

## What's incorrect or missing

[ Load Balancing](https://www.pomerium.com/assets/files/load-balancing-b987d141b50a843063b8daab0810dfdc.md) and  [configurations](https://www.pomerium.com/assets/files/load-balancing-b987d141b50a843063b8daab0810dfdc.md#active-health-checks) don't display page information correctly.

**Comment by ZPain8464** [comment]
PR here https://github.com/pomerium/documentation/pull/558

**Comment by ssveta7ak** [comment]
Fixed.
