### ISSUE TITLE
changelog heirarchy is busted

### ISSUE THREAD

**Issue by desimone** [pomerium/documentation#613]
Doc headers should be nested under version (see v0.20 vs v0.21 and v0.22)

<img width="205" alt="Screenshot 2023-05-05 at 3 25 26 PM" src="https://user-images.githubusercontent.com/1544881/236583539-933140de-799d-40b4-8397-22da5be20f5b.png">

[Slack Message](https://pomerium-com.slack.com/archives/C0277SH5KL3/p1683325545882139?thread_ts=1683325545.882139&cid=C0277SH5KL3)

**Comment by ZPain8464** [comment]
Resolved #620
