### ISSUE TITLE
clarify timeouts

### ISSUE THREAD

**Issue by wasaga** [pomerium/documentation#657]
Page: [Capabilities > Routing > Timeout](https://www.pomerium.com/docs/capabilities/routing#timeouts)

>websockets are long-lived connections, so [global timeouts](https://www.pomerium.com/docs/reference/global-timeouts) are not enforced

## What's incorrect or missing

Some global timeouts still apply. i.e. see 
- [this discussion.](https://pomerium-com.slack.com/archives/C04K947HB89/p1685646715661799)
- [another discussion](https://pomerium-io.slack.com/archives/CK92MUAES/p1685258918700619)

Also:
- timeout relationships (what influences what) are very confusing
- we have timeout options scattered all over the place

## What's the resolution?

1. Make a dedicated page about timeouts
2. Make a picture about timeouts elaborating the lifecycle of an HTTP request and which options apply to what (I believe we had one but it was deleted as we migrated to Envoy).

**Comment by desimone** [comment]
Let's create a similar diagram of timeouts to what we have before.

- https://0-10-0.docs.pomerium.com/reference/#global-timeouts

@wasaga  to supply the inputs of where the timeout spans start and end.
