### ISSUE TITLE
k8s: load balancing

### ISSUE THREAD

**Issue by wasaga** [pomerium/documentation#696]
Page: https://www.pomerium.com/docs/deploy/k8s/ingress#load-balancing

## What's incorrect or missing

1. Suggests visiting Reference LB page for details. 
2. Reference page suggests visiting the Ingress page for details. 

## What's the resolution?

Both pages should include concrete annotations syntax.

**Comment by desimone** [comment]
@ZPain8464  -- to create an epic / issue tracking a broader effort to verify kubernetes settings.
