### ISSUE TITLE
Identity and linkify links

### ISSUE THREAD

**Issue by alexfornuto** [pomerium/documentation#70]
in [K8sSettings.js](https://github.com/pomerium/documentation/blob/k8s-reference/src/components/K8sSettings.js) we [inject descriptions](https://github.com/pomerium/documentation/blob/k8s-reference/src/components/K8sSettings.js#L59) from the yaml spec.

The ask is to add a regex that detects URLs (`https://*`) and wraps them in html a tags pointing to the same URL.

**Comment by desimone** [comment]
@wasaga  -- Were you going to re-do the parsing of this in go as I recall?

**Comment by desimone** [comment]
Closed by https://app.zenhub.com/workspace/o/pomerium/ingress-controller/issues/428
