### ISSUE TITLE
ext data: document Record names

### ISSUE THREAD

**Issue by wasaga** [pomerium/documentation#76]
Page: /docs/enterprise/ext-data/

## What's incorrect or missing

[ ] which names could be used for Records 
[ ] are there reserved Record names that must not be used
[ ] what are the auto-created names for records obtained from archives?

**Comment by calebdoxsey** [comment]
There are no reserved names. We already document the format for record data. We have internal types we use but I don't think we should document them. They're not intended for user consumption. Its unclear to me what is desired here.

**Comment by calebdoxsey** [comment]
documented here: https://www.pomerium.com/docs/releases/enterprise/configure#external-data
