### ISSUE TITLE
policy: where to set it

### ISSUE THREAD

**Issue by wasaga** [pomerium/documentation#856]
Page: https://www.pomerium.com/docs/capabilities/ppl

## What's incorrect or missing

As a user, it is not exactly clear for me where the `policy` block should go. 

i.e. routes page https://www.pomerium.com/docs/capabilities/routing explains more niche things like load balancing, but does not tell you how to attach a policy to a route.

## What's the resolution?

cross link routes and ppl pages

**Comment by ZPain8464** [comment]
Related to #771
