### ISSUE TITLE
new logging configuration options

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/documentation#873]
We need to document two new configuration options: `access_log_fields` and `authorize_log_fields`.

Both of these options are represented as a list of fields (in core and the console). In JSON/YAML an array of strings. In environment variables as comma-separated.

```yaml
access_log_fields:
  - authority
  - duration
  - path

authorize_log_fields:
  - request-id
  - path
  - ip
``` 

Each field represents something that will appear in logs. For example the `path` field will add the HTTP path to the log entry.

Access logs are logs in the proxy service with a message of `http-request` like:

```json
{
  "level":"info",
  "service":"envoy",
  "time":"2023-07-25T14:59:18-06:00",
  "message":"http-request"
}
```

Authorization logs are logs in the authorize service with a message of `authorize check` like:

```json
{
  "level":"info",
  "service":"authorize",
  "allow":true,
  "allow-why-true":["user-ok"],
  "deny":false,
  "deny-why-false":[],
  "time":"2023-07-25T14:59:15-06:00",
  "message":"authorize check"
}
```

## Access Fields
The following access log fields are supported:

- `authority`: The HTTP Authority (AKA hostname, domain name), e.g. `www.example.com`
- `duration`: How long the request took in seconds
- `forwarded-for`: 
- `method`: The HTTP Method, e.g. `GET`, `POST`, `PUT`
- `path`: The HTTP Path, e.g. `/some/path`
- `query`: The HTTP Query, e.g. `a=b`
- `referer`: The HTTP Referer, e.g. `https://www.example.com/some/path`
- `request-id`: A unique identifier for the request
- `response-code`: The HTTP Response Code, e.g. `200`, `500`
- `response-code-details`: The HTTP Response Code Details, e.g. `File Not Found` for `404`
- `size`: The size of the HTTP Response
- `upstream-cluster`: The cluster the request was sent to
- `user-agent`: The User-Agent field sent by the user's browser
- `headers.{HeaderName}`: (core and console only) An HTTP Request Header identified by the `HeaderName`, e.g. `headers.X-Amzn-Trace-Id` might return something like `Root=1-64c03960-37809588421513e42f260f56`

The default access log fields are:

```yaml
- upstream-cluster
- method
- authority
- path
- user-agent
- referer
- forwarded-for
- request-id
- duration
- size
- response-code
- response-code-details
```

## Authorize Fields
The following authorize log fields are supported:
- `check-request-id`: The request ID of the gRPC check call
- `email`: The logged in user's email address
- `headers`: The complete set of HTTP request headers
- `headers.{HeaderName}`: (core and console only) same as above
- `host`: Same as `authority` above
- `id-token`: The user's ID token
- `id-token-claims`: The user's ID token claims
- `impersonate-email`: If impersonating, the impersonated email
- `impersonate-session-id`: If impersonating, the impersonated session id
- `impersonate-user-id`: If impersonating, the impersonated user id 
- `ip`: The user's IP address
- `method`: same as above
- `path`: same as above
- `query`: same as above
- `request-id`: same as above
- `service-account-id`: if using a service account, the service account id
- `session-id`: the session id 
- `user`: The user's ID

The default authorize log fields are:

```yaml
- request-id
- check-request-id
- method
- path
- host
- ip
- session-id
- impersonate-session-id
- impersonate-user-id
- impersonate-email
- service-account-id
- user
- email
```

**Comment by calebdoxsey** [comment]
Apologies, but the documentation as described above is not complete. The ingress controller and pomerium zero will have these fields configured in a different way. I will update the description.

**Comment by calebdoxsey** [comment]
Ok I have updated it as best as I understood. Unfortunately the configuration differences have nuances I don't quite grasp or can describe adequately.

**Comment by wasaga** [comment]
NB: for IC, we usually just link from main documentation to the relevant section of configuration reference page https://www.pomerium.com/docs/deploy/k8s/reference which is auto-generated from the spec.

**Comment by desimone** [comment]
There has been some churn on this. Is this still correct?
