### ISSUE TITLE
Google cache contains preview sites

### ISSUE THREAD

**Issue by wasaga** [pomerium/documentation#91]
Google cache contains preview sites. they should be excluded from search

<img width="988" alt="image" src="https://user-images.githubusercontent.com/673131/182174940-b6278d1b-92ca-4b3d-9fa4-5feaf0e8f9a1.png">

**Comment by desimone** [comment]
This isn't a preview site, but rather our old archived version. This still should be fixed, however with a robots.

**Comment by desimone** [comment]
Should be fixed by #190
